---
# handlers file for sonarr
- name: reload_firewalld
  systemd:
    name: firewalld
    state: reloaded
- name: empty_/opt/NzbDrone
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/opt/NzbDrone/*"
